# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vgcxCaZvJbewKF53acILfptQs4ohnPn1
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

print("Đang đọc dữ liệu gốc...")
df = pd.read_csv("dulieuxettuyendaihoc.csv")
print(f"Kích thước dữ liệu gốc: {df.shape}")

# Loại bỏ cột 'STT' và 'DT' không sử dụng cho mô hình học sâu
df_processed = df.drop(columns=["STT", "DT"])

# Lọc các cột chứa điểm số để chuẩn hóa MinMaxScaler
cac_cot_so = df_processed.select_dtypes(include=[np.number]).columns.tolist()

# Các cột phân loại cần chuyển đổi định dạng
cac_cot_chu = ["GT", "KV", "KT"]

print("\nĐang mã hóa One-Hot cho các cột phân loại...")
df_clean = pd.get_dummies(df_processed, columns=cac_cot_chu, dtype=float)

# Khởi tạo bộ tỷ lệ đưa dữ liệu về đoạn [0, 1]
print("\nĐang chuẩn hóa dữ liệu số...")
scaler = MinMaxScaler()
# Áp dụng chuẩn hóa lên toàn bộ các cột điểm số (bao gồm cả điểm cấp 3 và điểm đại học)
df_clean[cac_cot_so] = scaler.fit_transform(df_clean[cac_cot_so])

# Sắp xếp lại thứ tự các cột
danh_sach_cot_chuan = [
    "T1",
    "L1",
    "H1",
    "S1",
    "V1",
    "X1",
    "D1",
    "N1",
    "T2",
    "L2",
    "H2",
    "S2",
    "V2",
    "X2",
    "D2",
    "N2",
    "T3",
    "L3",
    "H3",
    "S3",
    "V3",
    "X3",
    "D3",
    "N3",
    "T4",
    "L4",
    "H4",
    "S4",
    "V4",
    "X4",
    "D4",
    "N4",
    "T5",
    "L5",
    "H5",
    "S5",
    "V5",
    "X5",
    "D5",
    "N5",
    "T6",
    "L6",
    "H6",
    "S6",
    "V6",
    "X6",
    "D6",
    "N6",
    "DH1",
    "DH2",
    "DH3",
    "GT_F",
    "GT_M",
    "KV_1",
    "KV_2",
    "KV_2NT",
    "KT_A",
    "KT_A1",
    "KT_B",
    "KT_C",
    "KT_D1",
]
df_clean = df_clean[danh_sach_cot_chuan]

# Xuất kết quả ra file sạch để làm đầu vào cho mạng ANN
ten_file_xuat = "dulieuxettuyendaihoc_clean.csv"
df_clean.to_csv(ten_file_xuat, index=False)

print(f"\n--- XỬ LÝ HOÀN TẤT ---")
print(f"Kích thước file sạch mới tạo: {df_clean.shape}")
print(f"Đã lưu file thành công tại: {ten_file_xuat}")
print("Dữ liệu hiển thị thử (5 dòng đầu):")
print(df_clean.head())