# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vrdo_8RMyOlW8AKh49QJhjng5S2wlyGX
"""

import tensorflow as tf
from tensorflow.keras import datasets, layers, models

# Bật cấu hình tối ưu hóa bộ nhớ đệm cho dữ liệu
autotune = tf.data.AUTOTUNE

# Tải dữ liệu CIFAR-10
(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()

# Chuẩn hóa dữ liệu
train_images, test_images = train_images / 255.0, test_images / 255.0

# Đóng gói dữ liệu bằng tf.data để tăng tốc xử lý song song
BATCH_SIZE = 256

train_dataset = tf.data.Dataset.from_tensor_slices((train_images, train_labels))
train_dataset = train_dataset.shuffle(buffer_size=50000).batch(BATCH_SIZE).prefetch(buffer_size=autotune)

test_dataset = tf.data.Dataset.from_tensor_slices((test_images, test_labels))
test_dataset = test_dataset.batch(BATCH_SIZE).prefetch(buffer_size=autotune)

# Kiến trúc mô hình CNN
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),

    layers.Conv2D(64, (3, 3), activation='relu'),

    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10)
])

# Biên dịch mô hình
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

# Huấn luyện với Dataset đã tối ưu
model.fit(train_dataset, epochs=10, validation_data=test_dataset)

# Đánh giá mô hình
test_loss, test_acc = model.evaluate(test_dataset, verbose=2)
print(f"\nĐộ chính xác trên tập kiểm tra: {test_acc * 100:.2f}%")